language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"

env:
  global:
    - DEBUG=wdio-screenshot:*
  matrix:
    - GRAPHICSMAGICK=true
    - GRAPHICSMAGICK=false

before_install:
  - if $if [ "$GRAPHICSMAGICK" = true ] ; then sudo apt-get update && sudo apt-get install graphicsmagick; fi

script:
  - npm run test
