# Test against these versions of Node.js.
environment:
  global:
      DEBUG: "wdio-screenshot:*"
  matrix:
    - nodejs_version: "0.12"
      GRAPHICSMAGICK: true
    - nodejs_version: "0.12"
      GRAPHICSMAGICK: false
    - nodejs_version: "4"
      GRAPHICSMAGICK: true
    - nodejs_version: "4"
      GRAPHICSMAGICK: false
    - nodejs_version: "5"
      GRAPHICSMAGICK: true
    - nodejs_version: "5"
      GRAPHICSMAGICK: false

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  # Install GraphicsMagick
  - ps: >-
      if ($env:GRAPHICSMAGICK -eq "true") {
        $((New-Object Net.WebClient).DownloadFile('http://downloads.sourceforge.net/graphicsmagick/GraphicsMagick-1.3.20-Q8-win32-dll.exe', "${pwd}\GraphicsMagick-1.3.20-Q8-win32-dll.exe") | Out-Host;$?) -and $(Start-Process -FilePath "${pwd}\GraphicsMagick-1.3.20-Q8-win32-dll.exe" -ArgumentList "/SP /VERYSILENT /NORESTART /NOICONS /DIR=${pwd}\gm" | Out-Host;$?)
        $env:Path = "${pwd}\gm;${env:Path}"
      }
  # Typical npm stuff.
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - cmd: npm run test

# Don't actually build.
build: off
